[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyroboplan"
version = "1.0.0"
dependencies = [
  "drake == 1.28.0",
  "pin == 2.7.0",
  "matplotlib == 3.8.4",
  "meshcat == 0.3.2",
  "scipy == 1.13.0",
  "trimesh == 4.4.0",
]
requires-python = ">=3.8"
authors = [
  {name = "Sebastian Castro", email = "sebas.a.castro@gmail.com"},
]
maintainers = [
  {name = "Sebastian Castro", email = "sebas.a.castro@gmail.com"},
]
description = "Educational Python library for manipulator motion planning."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["motion planning", "manipulators", "education"]
